version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    networks:
      - frontend
    volumes:
      - ./mongodb/data:/data/db


  bot: &bot
    build:
      context: bot
    depends_on:
      - mongodb
    restart: always
    networks:
      - frontend
    volumes:
      - ./app/app/cache:/app/cache


networks:
  frontend: